### ISSUE TITLE
Failing linters and rubocop configs

### ISSUE THREAD

**Issue by stvnjacobs** [ssplatt/kitchen-linode#8]
I was looking for your input on how you would like to handle this.

Currently, the .`rubocop.yml` file is out of date with recent versions of rubocop. Enough that it generates quite a few warnings and errors.

https://gist.github.com/stvnjacobs/5f62d21ffacfdd91a2e9ec4ba27e0b8d

Also, the checks that are currently run with Cane can be implemented in rubocop. The Cane project even recommends doing so.

https://github.com/square/cane#cane

I am thinking I would like to go back to rubocup defaults, only overriding them in `.rubocup.yml` where I think it makes sense. Then remove Cane and run the rubocop rake_task, fixing any immediate errors. Would you be in favor of this?

**Comment by ssplatt** [comment]
sure, this hasn't been updated in a long time and that config was probably copied from another opensource repo as an example. feel free to make any edits you think are reasonable to make it functional.

**Comment by testeddoughnut** [comment]
This can probably be closed out with the switch to `chefstyle` in #9.
